name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        # SHA: 67b44a8d51a1594c35b5222b56c76c64bff0ba72
        # https://github.com/actions/checkout/releases/tag/v4.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        # SHA: 0efed7e4658a5a6e74be25e3b03cecf65e3c0ec9
        # https://github.com/actions/setup-node/releases/tag/v4.0.2

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        # SHA: 3db6fc31bcbf36c42870946cf266e065b76e929d
        # https://github.com/actions/cache/releases/tag/v4.0.2

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # SHA: 67b44a8d51a1594c35b5222b56c76c64bff0ba72

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
        # SHA: 0efed7e4658a5a6e74be25e3b03cecf65e3c0ec9

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=high || true

  build:
    needs: [lint-and-test, audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # SHA: 67b44a8d51a1594c35b5222b56c76c64bff0ba72

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
        # SHA: 0efed7e4658a5a6e74be25e3b03cecf65e3c0ec9

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist
        # SHA: d00b6445d02899bd8d8b0208efb3083a416da47f
        # https://github.com/actions/upload-artifact/releases/tag/v4.3.1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Deploy placeholder
        run: echo "Deploy to production would go here"
