name: Test and Lint Workflow

on:
  workflow_call:
    inputs:
      node_versions:
        required: true
        type: string

jobs:
  matrix-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ fromJson(inputs.node_versions) }}

    steps:
      - uses: actions/checkout@a1b4a21e...
      - uses: actions/setup-node@d6d7ac...
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run lint
